import { useEffect, useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { db } from '../firebase';
import { ref, onValue, push, serverTimestamp, set } from 'firebase/database';
import Sidebar from '../components/Sidebar';
import MessageList from '../components/MessageList';
import Composer from '../components/Composer';
import { TopBanner, RightRail, MobileAdTab } from '../components/Ads';
import { initIdle } from '../utils/idle';
export default function Home(){const nav=useNavigate();const [currentRoom,setCurrentRoom]=useState<string>('');const [roomsReady,setRoomsReady]=useState(false);const [roomMeta,setRoomMeta]=useState<any>(null);useEffect(()=>{const off=onValue(ref(db,'/rooms'),async snap=>{let v=snap.val();if(!v){const defaults=[['Late Night Talk','🌙'],['Global Traveler','✈️'],['Coffee Corner','☕'],['Wellness Hub','🌿'],['Developer Lab','💻']];for(const [name,icon] of defaults){const r=push(ref(db,'/rooms'));const id=r.key!;await set(ref(db,`/rooms/${id}`),{name,icon,isOfficial:true,visibility:'public',ownerId:'system',createdAt:serverTimestamp(),updatedAt:serverTimestamp(),welcome:`Welcome to ${name}!`})}v=(await (await import('firebase/database')).get(ref(db,'/rooms'))).val()}const first=Object.keys(v)[0];setCurrentRoom(first);setRoomsReady(true)});return()=>off()},[]);useEffect(()=>{if(!currentRoom)return;const off=onValue(ref(db,`/rooms/${currentRoom}`),snap=>setRoomMeta(snap.val()));return()=>off()},[currentRoom]);useEffect(()=>{const stop=initIdle(()=>{nav('/')},40*60*1000);return stop},[]);if(!currentRoom&&!roomsReady)return null;return(<div className='min-h-screen text-white flex flex-col'><TopBanner/><div className='flex-1 flex'><Sidebar currentRoom={currentRoom} onSelectRoom={setCurrentRoom}/><div className='flex-1 flex flex-col'><div className='h-14 flex items-center justify-between px-4 border-b border-white/10 bg-black/40'><div className='flex items-center gap-2'><span>{roomMeta?.icon||'💬'}</span><div className='font-semibold'>{roomMeta?.name||currentRoom}</div>{roomMeta?.isOfficial?<span className='badge'>Official</span>:<span className='badge'>{roomMeta?.visibility||'public'}</span>}<button className='ml-3 text-xs bg-white/10 px-2 py-1 rounded' onClick={()=>alert(roomMeta?.welcome||'Welcome!')}>Welcome</button><button className='ml-1 text-xs bg-white/10 px-2 py-1 rounded' onClick={()=>alert('Members panel TBD')}>Members</button></div><div className='text-white/70 text-sm'>ChatSphere</div></div><MessageList path={`/messages/${currentRoom}`}/><Composer target={{roomId:currentRoom}}/></div><RightRail/></div><MobileAdTab/></div>)}
