name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Install deps
        run: pnpm install

      - name: Build
        env:
          NODE_ENV: production
        run: pnpm run build

      - name: List dist directory
        run: |
          echo "=== dist directory ==="
          ls -la dist/ || echo "dist not found"
          echo "=== dist/sfx directory ==="
          ls -la dist/sfx/ || echo "sfx not found"

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          force_orphan: true
